# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc24b48820f3ccf156dd7610b63c7a6557b3d032a3f630b1764c006b743da9a78d5f88694614087bc20c719ffcecb936c938f77ea5967b778047d5751feda9e7

test:
  secret_key_base: f13c4a130b1f691f93a7f8295cef3a7ed7ad934f4c5b440062b5d3b7be36acb4de362255f5dbb9f9cebedd59ddb95b9e32b623f98284b9a4c367ee09400896db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
