# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92c0dace8f05bdb036d852edd51cf714ae300426c74a6bb30fd37ad9448bfe53454714701845a53f4059afe718501255b3937599294b0ce85b7518348095ff4e

test:
  secret_key_base: ea2f74b4a72024755b3d603776f09ae8d451b439ee366b29f8f1a596cf992ddf4c456acee1e28e8e42b2a4ef3c5c4f7636e4e4b1544cf974dce82d1f1c2ddbe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
